receivers:
  docker_stats:
    endpoint: "unix:///var/run/docker.sock"
    collection_interval: 15s
    initial_delay: 5s
    excluded_images:
      - metrics-aggregator
      - moby/buildkit:buildx-stable-1
      - otel/opentelemetry-collector-contrib:latest

processors:
  batch:

exporters:
  otlp_grpc:
    endpoint: "metrics-aggregator:4317"
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [docker_stats]
      processors: [batch]
      exporters: [otlp_grpc]